inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7.2

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
